### PR TITLE
Fixed typos on Angular and simplified sentence at the end

### PR DESCRIPTION
**Pull request by uglow**
Hi Kent, 

Just some minor typos to consider. Overall, very good article.

I went to ng-conf 2015 and your workshop - great job there! I'm also the guy that didn't get a chance to follow up with you regarding [angular-form-lib](http://uglow.github.io/angular-form-lib/). I'm interested to hear what you think of the form-policy concept, and how the form properties work together to support ARIA, including reading out error messages.

One last thing - would you be able to review my [air-pair article](https://www.airpair.com/posts/contributors/54fa8d6e658b7d0c00a4eddb) too, please?

Cheers,
Brett

### CODE REVIEW

**Comment by kentcdodds** [comment]
The form-policy concept is neat because it allows users to have much more control over the state of the form and that's handy. I don't know a ton about what I need more than what ngAria gives me with regards to forms. I believe ngAria provides the tags I need for the error messages to be read out, and I know it places the proper tags on the `ng-model` elements based on their state.

Thanks for the edits. All great!

**Comment by kentcdodds** [comment]
Do you know how I review your post? I don't see any control that would let me see it...

screen shot 2015-03-09 at 5 52 11 am

**Comment by jkresner** [comment]
You have to type something in....

On Monday, March 9, 2015, Kent C. Dodds notifications@github.com wrote:

> Do you know how I review your post? I don't see any control that would let
> me see it...
> 
> [image: screen shot 2015-03-09 at 5 52 11 am]
> https://cloud.githubusercontent.com/assets/1500684/6554365/742e1bac-c620-11e4-92be-6a3319db53c8.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/ngmodeloptions-total-model-control/pull/1#issuecomment-77840216
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by kentcdodds** [comment]
@jkresner, why would I type something in? I haven't read the post yet. Where do I see the post?

**Comment by jkresner** [comment]
I see good point. I'll update the UX. You can find it here

https://www.airpair.com/posts/in-community-review

On Monday, March 9, 2015, Kent C. Dodds notifications@github.com wrote:

> @jkresner https://github.com/jkresner, why would I type something in? I
> haven't read the post yet? Where do I see the post?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/ngmodeloptions-total-model-control/pull/1#issuecomment-77888176
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by uglow** [comment]
Thanks for the feedback, Kent!

**Pull request merged**
