### PR TITLE
Fix syntax highlighting

### PR DESCRIPTION
**Pull request by jkresner**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Could you update this post? Thanks!

**Comment by jkresner** [comment]
done
ᐧ

On Sat, Mar 14, 2015 at 1:57 PM, Kent C. Dodds notifications@github.com
wrote:

> Could you update this post? Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/ngmodeloptions-total-model-control/pull/2#issuecomment-80718949
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by kentcdodds** [comment]
Awesome! 5 stars? :-) Unless there's something else to make this post awesome :-)

**Comment by jkresner** [comment]
Sorry haven't had a chance to look at it again. Will soon :)
ᐧ

On Sat, Mar 14, 2015 at 2:16 PM, Kent C. Dodds notifications@github.com
wrote:

> Awesome! 5 stars? :-) Unless there's something else to make this post
> awesome :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/ngmodeloptions-total-model-control/pull/2#issuecomment-80721151
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Pull request merged**
